import {Inter} from 'next/font/google';
import './globals.css';
import TypekitLoader from './_utils/TypekitLoader';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'soraneko',
  description: 'Generated by create next app',
};

export default function RootLayout({children, modal}) {
  return (
    <html lang="ja" suppressHydrationWarning={true}>
      <TypekitLoader />
      <body className={inter.className} suppressHydrationWarning={true}>
        {children}
        {modal}
      </body>
    </html>
  );
}
